sources:
    - name: divvy_trip_app
      database: divvy_trip
      schema: default
      tables:
        - name: 202401_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_tests:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202402_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202403_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202404_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202405_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202406_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202407_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202408_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202409_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202410_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202411_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]
        - name: 202412_divvy_tripdata
          columns:
            - name: ride_id
              data_tests:
                - unique
                - not_null
            - name: started_at
              data_tests:
                - not_null
            - name: ended_at
              data_test:
                - not_null
            - name: rideable_type
              data_tests:
                - not_null
            - name: member_casual
              data_tests:
                - accepted_values:
                    arguments:
                      values: ["member", "casual"]